
env: "local"
postgres:
  host: "localhost"
  port: 5432
  user: "sso_user"
  password: "sso_password"
  dbname: "sso_db"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"
grpc:
  port: 44044
  timeout: 10h