env: "local_tests"
postgres:
  host: "localhost"
  port: 5432
  user: "test_user"
  password: "test_password"
  dbname: "sso_test_db"
  sslmode: "disable"
  max_open_conns: 10
  max_idle_conns: 2
  conn_max_lifetime: "1m"
grpc:
  port: 44045
  timeout: 5m