env: "prod"
postgres:
  host: "${POSTGRES_HOST}"
  port: 5432
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  dbname: "${POSTGRES_DB}"
  sslmode: "require"
  max_open_conns: 100
  max_idle_conns: 25
  conn_max_lifetime: "30m"
grpc:
  port: 44044
  timeout: 30s